### ISSUE TITLE
Could you share me the goole drive urls of LRS2 and LRS3 dataset? Thank you very much!

### ISSUE THREAD

**Issue by MPQZF** [ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild#11]

**Comment by ms-dot-k** [comment]
I don't have permission to distribute this. Please find the official site.

LRS2 - https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html
LRS3- https://mmai.io/datasets/lip_reading/
