### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by aspirinone** [ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild#4]
Now the data sets of LRS2 and LRS3 cannot be obtained from the official website. Specifically, the mailbox rob.cooper@bbc.co.uk cannot be delivered. Could the author provide the web disk of the data sets?

**Comment by ms-dot-k** [comment]
It is prohibited to redistribute the dataset, so I cannot help you.
But, the LRS3 dataset can be downloaded from https://mmai.io/datasets/lip_reading/
