### ISSUE TITLE
Incorrect LRS2 data splits download link

### ISSUE THREAD

**Issue by 1889737514** [ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild#8]
Hello, I find that the download link in data splits of LRS2 is same with the link of lip coordinate. Can you upload correct files?

**Comment by ms-dot-k** [comment]
Hello, the splits are not from us, they are from the original dataset. 
You can find them on https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html .

**Comment by 1889737514** [comment]
OK, thank you!
