### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by Buicongbang04** [ms-dot-k/Lip-to-Speech-Synthesis-in-the-Wild#9]
Hello author, congratulate you on this project. I have a question, I wanna run your repo on another data, like run inference. How can I do that ? Can you guide me ?

**Comment by ms-dot-k** [comment]
The pre-trained models are based on LRS2 and LRS3, which have already well-shaped.
The model is trained by cropping the video with 80 x 80 size centered by the lip landmark coordination (LRS2).

Hence, if you want to apply the pre-trained model to another dataset, you need to align your video to have the same face size with that of LRS2. And then you can crop the video at 80 x 80 size centered by the lip landmark coordinates.
